---
services:
  db:
    image: docker.io/library/postgres:15-alpine
    environment:
      POSTGRES_DB: digigoods
      POSTGRES_USER: digigoods
      POSTGRES_PASSWORD: digigoods
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U digigoods -d digigoods"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/digigoods
      SPRING_DATASOURCE_USERNAME: digigoods
      SPRING_DATASOURCE_PASSWORD: digigoods
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
